[WIP] validate k8s version for out-of-service-taint remediation strategy
medik8s/self-node-remediation pull request #104
Opened 2023-04-02 11:41 UTC by mshitrit

Verifying out of service taint is supported before allowing the user to set it.

2023-04-02 17:32 UTC, mshitrit commented
/retest

2023-04-02 19:37 UTC, mshitrit commented
/override ci/prow/4.11-openshift-e2e

2023-04-03 08:48 UTC, slintes requested changes
As discussed, the k8s version alone does not guarantee that the feature is enabled. However, this still is valueable.
Some comments inline.

2023-04-03 08:48 UTC, slintes commented on api/v1alpha1/selfnoderemediationtemplate_webhook.go
> +	minK8sVersionSupportingOutOfServiceTaint = 1.26
nit: this should be a const

2023-04-03 08:48 UTC, slintes commented on api/v1alpha1/selfnoderemediationtemplate_webhook.go
> +		k8sVersion, err := strconv.ParseFloat(fmt.Sprintf("%s.%s", version.Major, version.Minor), 8)
I'm always afraid of rounding errors when using float... I guess even more with that low bitsize? ~~Maybe validate major and minor each? I think `major > 1 || minor >= 26`~~ Even better, there is a `semver` package 🙂

2023-04-03 08:48 UTC, slintes commented on api/v1alpha1/selfnoderemediationtemplate_webhook_test.go
> +					err := outOfServiceStrategy.ValidateCreate()
nit: could be reduced to `Expect(outOfServiceStrategy.ValidateCreate()).To(MatchError(ContainSubstring("OutOfServiceTaint remediation strategy is not supported at kubernetes version lower than 1.26, please use a different remediation strategy")))`

2023-04-03 11:36 UTC, slintes requested changes

2023-04-03 11:44 UTC, mshitrit commented on api/v1alpha1/selfnoderemediationtemplate_webhook.go
> +		if majorVer, err = strconv.ParseInt(version.Major, 10, 8); err != nil {
Yep Atoi is nicer, I guess I was caught up on `ParseInt` because I saw it's used in semver :slightly_smiling_face:

2023-04-03 11:47 UTC, slintes approved these changes

2023-04-03 13:33 UTC, merged