Update SNR versions
medik8s/self-node-remediation pull request #12
Opened 2022-04-13 13:17 UTC by mshitrit

**First** Commit:
Go 1.18
operator-sdk 1.19.0
kustomize 4.5.4
controller-gen 0.8.0
envtest k8s 1.23
**Second** Commit:
go mod vendor

2022-04-13 15:44 UTC, slintes requested changes

2022-04-13 15:44 UTC, slintes commented on Makefile
> +	KUBEBUILDER_ASSETS="$(shell $(ENVTEST) use $(ENVTEST_K8S_VERSION) -p path --bin-dir $(PROJECT_DIR)/testbin)" go test ./controllers/... -coverprofile cover.out -v -ginkgo.v
you probably want to add the `pkg` package to the packages to test

2022-04-13 15:44 UTC, slintes commented on Makefile
> +GOBIN=$(PROJECT_DIR)/bin go get $(2) ;\
the `go get` line be deleted

2022-04-15 09:29 UTC, mshitrit commented
/retest

2022-04-17 15:37 UTC, razo7 commented on .github/workflows/post-submit.yaml
> +        uses: actions/setup-go@v2
I think it should be version 3 (see [here](https://github.com/actions/setup-go)).

2022-04-19 18:07 UTC, slintes commented on Makefile
> +	KUBEBUILDER_ASSETS="$(shell $(ENVTEST) use $(ENVTEST_K8S_VERSION) -p path --bin-dir $(PROJECT_DIR)/testbin)" go test ./controllers/... -coverprofile cover.out -v -ginkgo.v
@mshitrit Please also add the api package, so we will run the soon-to-be-merged new webhook tests as well.
@shellykatz fyi

2022-04-25 07:29 UTC, mshitrit commented
/retest

2022-04-28 18:40 UTC, mshitrit commented
/retest

2022-04-29 07:08 UTC, mshitrit commented
/retest

2022-05-02 07:18 UTC, slintes approved these changes

2022-05-02 07:20 UTC, merged