override default node selector in suggested namespace
medik8s/self-node-remediation pull request #168
Opened 2023-12-06 13:18 UTC by mshitrit

ECOPROJECT-1783
override the default node selector, in order to make sure that SNR node selector which is defined in the Daemonset will take precedence.

2023-12-06 13:52 UTC, mshitrit commented
/test 4.12-openshift-e2e

2023-12-07 14:45 UTC, slintes requested changes
Can you test please what happens when the namespace already exists without that annotation? If it isn't added, we should add it to the other operators as well, and need to document it.

2023-12-07 14:45 UTC, slintes commented on bundle/manifests/self-node-remediation.clusterserviceversion.yaml
> +    operatorframework.io/suggested-namespace-template: |-
we need to keep `operatorframework.io/suggested-namespace`, the template is new OCP 4.13

2023-12-19 15:03 UTC, mshitrit commented
> Can you test please what happens when the namespace already exists without that annotation? If it isn't added, we should add it to the other operators as well, and need to document it.

I've done a quick test:
- created a catsrc with the new version (after I've already created the ns)
- installed snr from that catsrc

As far as I can see the annotation wasn't added to the ns.

However I've also did a simpler test, installing the operator when the ns didn't exist and I saw the same result :sweat_smile: 

since the namesapce was created and the pods where created in the correct ns I'm thinking that only `operatorframework.io/suggested-namespace:` annotation was proccessed from the csv and not `operatorframework.io/suggested-namespace-template:` but it needs furtther investigation.

2023-12-19 17:43 UTC, slintes commented
> > Can you test please what happens when the namespace already exists without that annotation? If it isn't added, we should add it to the other operators as well, and need to document it.
> 
> I've done a quick test:
> 
> * created a catsrc with the new version (after I've already created the ns)
> * installed snr from that catsrc
> 
> As far as I can see the annotation wasn't added to the ns.
> 
> However I've also did a simpler test, installing the operator when the ns didn't exist and I saw the same result 😅
> 
> since the namesapce was created and the pods where created in the correct ns I'm thinking that only `operatorframework.io/suggested-namespace:` annotation was proccessed from the csv and not `operatorframework.io/suggested-namespace-template:` but it needs furtther investigation.

just to be sure, you installed using the console in both cases, right? 🙂

2023-12-20 07:04 UTC, mshitrit commented
>just to be sure, you installed using the console in both cases, right? 🙂

Indeed I have

2023-12-20 13:51 UTC, mshitrit commented
/retest

2023-12-20 15:32 UTC, mshitrit commented
After modifying the format of `operatorframework.io/suggested-namespace-template` I've managed to properly test it.
- In case the namespace does not exit the annotation is added as expected.
- Otherwise it isn't.

I've updated the related epic: https://issues.redhat.com/browse/ECOPROJECT-1761 
@clobrano I see that so far it was only implemented in MDR so make sure to update as well.

2023-12-20 15:54 UTC, slintes commented
> * In case the namespace does not exit the annotation is added as expected.
> * Otherwise it isn't.
> 

too bad, thanks for checking!

There seems to be an unrelated code change, otherwise lgtm

2023-12-21 06:55 UTC, mshitrit commented on controllers/selfnoderemediation_controller.go
> +	_, isUnrecognisableError := err.(*UnreconcilableError)
Just a minor typo fix.

2023-12-21 06:56 UTC, mshitrit commented
/retest

2023-12-21 08:49 UTC, mshitrit commented
/retest

2023-12-25 11:43 UTC, razo7 commented
/lgtm

2023-12-25 11:46 UTC, merged