[WIP] update base image to ubi9
medik8s/self-node-remediation pull request #201
Opened 2024-05-20 08:50 UTC by mshitrit

#### Why we need this PR

#### Changes made

#### Which issue(s) this PR fixes

#### Test plan

2024-05-20 10:53 UTC, razo7 commented
/lgtm and please update the PR description

2024-05-20 10:54 UTC, razo7 commented
/lgtm

2024-05-20 10:57 UTC, mshitrit commented
/test 4.15-openshift-e2e

2024-05-21 05:20 UTC, razo7 commented
seems like a chicken and egg problem, but don't forget to update CI afterward for using the UBI9 base image (in https://github.com/openshift/release/blob/master/ci-operator/config/medik8s/self-node-remediation/medik8s-self-node-remediation-main__4.12.yaml#L5 and in similar places)

2024-05-21 06:47 UTC, slintes commented on Dockerfile
> +FROM registry.access.redhat.com/ubi9/ubi:latest
not an issue as long as we build a statically linked binary AFAIK, but I think it's better to update the builder image to centos:stream9 as well

2024-05-22 09:07 UTC, slintes commented
This is using the wrong Go version 😞 
From the image job:
```
[...]
2024-05-22T08:16:41.825834595Z   Installing       : golang-1.22.2-1.el9.x86_64                         106/107 
[...]
2024-05-22T08:16:43.170425063Z [1/2] STEP 7/18: ENV GOTOOLCHAIN=auto
2024-05-22T08:16:43.215108442Z [1/2] STEP 8/18: RUN export GO_VERSION=$(grep -E "go [[:digit:]]\.[[:digit:]][[:digit:]]" go.mod | awk '{print $2}') &&     go get go@${GO_VERSION} &&     go version
2024-05-22T08:16:44.051438329Z go: upgraded go 1.21 => 1.21.10
2024-05-22T08:16:44.051438329Z go: added toolchain go1.22.2
2024-05-22T08:16:44.063705553Z go version go1.22.2 (Red Hat 1.22.2-1.el9) linux/amd64
```
We've seen this before, I'd suggest to install Go from `go.dev` like we do in NHC already: https://github.com/medik8s/node-healthcheck-operator/blob/main/Dockerfile#L12-L26

2024-05-22 15:36 UTC, mshitrit commented
/retest

2024-05-22 15:38 UTC, mshitrit commented
/test 4.13-test

2024-05-23 07:08 UTC, slintes requested changes

2024-05-23 07:08 UTC, slintes commented on Dockerfile
> +RUN yum install git golang jq -y && yum clean all
you can remove go here :)

2024-05-28 07:13 UTC, merged