[WIP] Verify there is no more than one configuration
medik8s/self-node-remediation pull request #203
Opened 2024-05-28 10:40 UTC by mshitrit

#### Why we need this PR
SNR has a maximum of one agent created by it's daemonset on each node.
All of these agents are using a single configuration, therefore having more than one configuration may cause an unexpected behavior.
ATM there is no limitation on creating multiple SNR configuration, the purpose of this PR is to make sure there will be no more than one configuration for SNR.

#### Changes made
- Added a unique  annotation on the default configuration.
- Added a validation on creation of a configuration that this annotation exist, otherwise the create is rejected.

#### Which issue(s) this PR fixes
ECOPROJECT-1997

If there is not a correspondent issue yet, you might want to open a new one yourself, describing the problem you observed.
-->

#### Test plan

2024-05-28 11:48 UTC, razo7 commented on api/v1alpha1/selfnoderemediationconfig_webhook.go
> +	return fmt.Errorf("only single configuration is allowed")
NIT: maybe be more specific?
```suggestion
	return fmt.Errorf("only single SNRConfig is allowed in the cluster")
```

2024-05-28 13:18 UTC, mshitrit commented on api/v1alpha1/selfnoderemediationconfig_webhook.go
> +}
Very good points.
I agree documentation is indeed required.
Regarding the name how about using `IsSingeltonConfigurationAnnotation = "is-singelton-configuration.self-node-remediation.medik8s.io"` ?

2024-05-28 13:27 UTC, clobrano commented on api/v1alpha1/selfnoderemediationconfig_webhook.go
> +}
It's surely better, however I still feel we're not really doing much with this change :sweat_smile: 
If we need documentation anyway, maybe just the documentation will be enough :shrug:

2024-05-29 06:41 UTC, slintes commented on api/v1alpha1/selfnoderemediationconfig_webhook.go
> +}
And how do docs prevent creation of multiple configs with that annotation?
IMHO the only way to fix the issue is to use a hardcoded name for the config, and prevent creation of configs with any other name...

2024-05-29 06:57 UTC, slintes commented on api/v1alpha1/selfnoderemediationconfig_webhook.go
> +}
suggestion: 
- use `cluster` (edit: nope, that will break existing configs, use what we used so far) as name, that's what OCP uses as well for cluster wide configs. Can be enforced with kubebuilder by making it an enum with a single value
- validating webhook just ensures that it's in the same namespace as the operator

2024-05-30 07:04 UTC, mshitrit commented on api/v1alpha1/selfnoderemediationconfig_webhook.go
> +}
Nice idea of using a hard coded name + validate the ns :+1:

2024-06-02 11:10 UTC, mshitrit commented
/test ?

2024-06-02 11:10 UTC, mshitrit commented
/test 4.15-openshift-e2e

2024-06-04 15:02 UTC, clobrano requested changes
I left one minimal comment, otherwise lgtm

2024-06-04 16:17 UTC, clobrano approved these changes

2024-06-04 16:18 UTC, clobrano commented
Giving a chance to get more reviews
/hold

2024-06-04 16:21 UTC, mshitrit commented
/test 4.15-openshift-e2e

2024-06-04 17:08 UTC, slintes approved these changes

2024-06-05 12:00 UTC, mshitrit commented
/unhold

2024-06-05 12:56 UTC, merged